// ================================================
// SS CRACKERS - PRODUCTS DATA
// Complete Price List from Excel
// ================================================

const PRODUCTS = [
  // ---- BIJILI / BOMBS ----
  { id: 1, name: "2 3/4 KURUVI", mrp: 55, price: 11, category: "bijili", emoji: "💥" },
  { id: 2, name: "3 1/2 LAKSHMI", mrp: 70, price: 14, category: "bijili", emoji: "💥" },
  { id: 3, name: "4\" LAKSHMI", mrp: 120, price: 24, category: "bijili", emoji: "💥" },
  { id: 4, name: "4\" DELUXE PANDA/HULK", mrp: 160, price: 32, category: "bijili", emoji: "💥" },
  { id: 5, name: "5\" DELUX", mrp: 230, price: 46, category: "bijili", emoji: "💥" },
  { id: 6, name: "6\" MEGA", mrp: 400, price: 80, category: "bijili", emoji: "💥" },
  { id: 7, name: "2 SOUND", mrp: 150, price: 30, category: "bijili", emoji: "💥" },
  { id: 8, name: "GOLD LAKSHMI", mrp: 195, price: 39, category: "bijili", emoji: "💥" },
  { id: 9, name: "RED BIJILI (50 PCS)", mrp: 105, price: 21, category: "bijili", emoji: "💥" },
  { id: 10, name: "STRIPPED BIJILI (50 pcs)", mrp: 115, price: 23, category: "bijili", emoji: "💥" },
  { id: 11, name: "RED BIJILI (100 PCS)", mrp: 225, price: 45, category: "bijili", emoji: "💥" },
  { id: 12, name: "STRIPPED BIJILI (100 pcs)", mrp: 145, price: 29, category: "bijili", emoji: "💥" },

  // ---- CHORSHA / DELUX ----
  { id: 13, name: "28 CHORSHA", mrp: 100, price: 20, category: "bijili", emoji: "🧨" },
  { id: 14, name: "28 GIANT", mrp: 150, price: 30, category: "bijili", emoji: "🧨" },
  { id: 15, name: "56 GIANT", mrp: 300, price: 60, category: "bijili", emoji: "🧨" },
  { id: 16, name: "24 DELUX", mrp: 270, price: 54, category: "bijili", emoji: "🧨" },
  { id: 17, name: "50 DELUX", mrp: 650, price: 130, category: "bijili", emoji: "🧨" },
  { id: 18, name: "100 DELUX", mrp: 1480, price: 296, category: "bijili", emoji: "🧨" },

  // ---- FLOWER POTS ----
  { id: 19, name: "FLOWER POTS SMALL", mrp: 275, price: 55, category: "flower", emoji: "🌸" },
  { id: 20, name: "FLOWER POTS BIG", mrp: 430, price: 86, category: "flower", emoji: "🌸" },
  { id: 21, name: "FLOWER POTS SPECIAL", mrp: 580, price: 116, category: "flower", emoji: "🌸" },
  { id: 22, name: "FLOWER POTS ASHOKA", mrp: 795, price: 159, category: "flower", emoji: "🌸" },
  { id: 23, name: "FLOWER POTS DELUX", mrp: 1245, price: 249, category: "flower", emoji: "🌸" },
  { id: 24, name: "COLOR KOTI", mrp: 1200, price: 240, category: "flower", emoji: "🌺" },
  { id: 25, name: "COLOUR KOTI MEGA", mrp: 2200, price: 440, category: "flower", emoji: "🌺" },

  // ---- GROUND CHAKKRA ----
  { id: 26, name: "CHAKKRA BIG", mrp: 250, price: 50, category: "chakkra", emoji: "🌀" },
  { id: 27, name: "CHAKKRA SPL", mrp: 400, price: 80, category: "chakkra", emoji: "🌀" },
  { id: 28, name: "CHAKKRA ASHOKA", mrp: 330, price: 66, category: "chakkra", emoji: "🌀" },
  { id: 29, name: "CHAKKRA DELUX", mrp: 810, price: 162, category: "chakkra", emoji: "🌀" },
  { id: 30, name: "DISCO WHEEL", mrp: 600, price: 120, category: "chakkra", emoji: "🌀" },
  { id: 31, name: "WISHING WHEEL", mrp: 995, price: 199, category: "chakkra", emoji: "🌀" },
  { id: 32, name: "4*4 STAR WHEEL", mrp: 1300, price: 260, category: "chakkra", emoji: "⭐" },
  { id: 33, name: "MOTO WHEEL", mrp: 1300, price: 260, category: "chakkra", emoji: "🌀" },
  { id: 34, name: "CHAKKAR CELEBRATION", mrp: 3495, price: 699, category: "chakkra", emoji: "🎇" },

  // ---- BOMBS ----
  { id: 35, name: "BULLET BOMB", mrp: 230, price: 46, category: "bijili", emoji: "💣" },
  { id: 36, name: "KING BOMB", mrp: 400, price: 80, category: "bijili", emoji: "💣" },
  { id: 37, name: "CLASSIC BOMB", mrp: 600, price: 120, category: "bijili", emoji: "💣" },
  { id: 38, name: "JURASSIC BOMB", mrp: 670, price: 134, category: "bijili", emoji: "💣" },
  { id: 39, name: "SPIDER BOMB", mrp: 1300, price: 260, category: "bijili", emoji: "💣" },
  { id: 40, name: "GORILLA BOMB", mrp: 530, price: 106, category: "bijili", emoji: "💣" },
  { id: 41, name: "MEGA DTS BOMB", mrp: 1200, price: 240, category: "bijili", emoji: "💣" },
  { id: 42, name: "MEGA 555 BOMB", mrp: 1100, price: 220, category: "bijili", emoji: "💣" },
  { id: 43, name: "WORLD WAR", mrp: 1100, price: 220, category: "bijili", emoji: "💣" },

  // ---- TWINKLING STARS / CANDLES ----
  { id: 44, name: "3\" Twinkling Star", mrp: 210, price: 42, category: "fancy", emoji: "⭐" },
  { id: 45, name: "4\" Twinkling Star", mrp: 480, price: 96, category: "fancy", emoji: "⭐" },
  { id: 46, name: "Ultra Pencil", mrp: 360, price: 72, category: "fancy", emoji: "✏️" },
  { id: 47, name: "Magic Candle", mrp: 1245, price: 249, category: "fancy", emoji: "🕯️" },
  { id: 48, name: "Smart Candle", mrp: 1300, price: 260, category: "fancy", emoji: "🕯️" },

  // ---- ROCKETS ----
  { id: 49, name: "Rocket Bomb", mrp: 320, price: 64, category: "rocket", emoji: "🚀" },
  { id: 50, name: "Two Sound Rocket", mrp: 680, price: 136, category: "rocket", emoji: "🚀" },
  { id: 51, name: "Whistling Rocket", mrp: 1100, price: 220, category: "rocket", emoji: "🚀" },

  // ---- PAPER BOMBS ----
  { id: 52, name: "Single Paper Bomb", mrp: 400, price: 80, category: "bijili", emoji: "💥" },
  { id: 53, name: "Colour Paper Bomb", mrp: 400, price: 80, category: "bijili", emoji: "💥" },
  { id: 54, name: "Mega Paper Bomb", mrp: 800, price: 160, category: "bijili", emoji: "💥" },
  { id: 55, name: "Old Is Gold Colour Paper", mrp: 1200, price: 240, category: "bijili", emoji: "💥" },

  // ---- AERIAL / SKY SHOTS ----
  { id: 56, name: "12 Shot Rider", mrp: 745, price: 149, category: "aerial", emoji: "🎆" },
  { id: 57, name: "12 Shot Multicolour", mrp: 995, price: 199, category: "aerial", emoji: "🎆" },
  { id: 58, name: "15 Shot Multicolour", mrp: 1345, price: 269, category: "aerial", emoji: "🎆" },
  { id: 59, name: "25 Shot Rider", mrp: 1495, price: 299, category: "aerial", emoji: "🎆" },
  { id: 60, name: "25 Shot Multicolour", mrp: 1745, price: 349, category: "aerial", emoji: "🎆" },
  { id: 61, name: "30 Shot Multicolour", mrp: 2750, price: 550, category: "aerial", emoji: "🎆" },
  { id: 62, name: "60 Shot Multicolour", mrp: 5500, price: 1100, category: "aerial", emoji: "🎆" },
  { id: 63, name: "100 Shot Multicolour", mrp: 9000, price: 1800, category: "aerial", emoji: "🎆" },
  { id: 64, name: "120 Shot Multicolour", mrp: 9995, price: 1999, category: "aerial", emoji: "🎆" },
  { id: 65, name: "240 Shot Multicolour", mrp: 18500, price: 3700, category: "aerial", emoji: "🎆" },
  { id: 66, name: "520 Shot Multicolour", mrp: 34995, price: 6999, category: "aerial", emoji: "🎆" },

  // ---- SINGLE PIPES ----
  { id: 67, name: "2 Inch Single Pipe", mrp: 780, price: 156, category: "aerial", emoji: "🎇" },
  { id: 68, name: "2.5 Inch Single Pipe", mrp: 840, price: 168, category: "aerial", emoji: "🎇" },
  { id: 69, name: "3 Inch Single Pipe", mrp: 1360, price: 272, category: "aerial", emoji: "🎇" },
  { id: 70, name: "3.5 Inch Single Pipe", mrp: 1440, price: 288, category: "aerial", emoji: "🎇" },
  { id: 71, name: "4 Inch Single Pipe", mrp: 1640, price: 328, category: "aerial", emoji: "🎇" },
  { id: 72, name: "3.5 Inch Double Ball", mrp: 2495, price: 499, category: "aerial", emoji: "🎇" },
  { id: 73, name: "4\" Double Pack", mrp: 4100, price: 820, category: "aerial", emoji: "🎇" },
  { id: 74, name: "4\" Spl Window Pack", mrp: 2680, price: 536, category: "aerial", emoji: "🎇" },
  { id: 75, name: "3\" Spl Window Pack", mrp: 1800, price: 360, category: "aerial", emoji: "🎇" },
  { id: 76, name: "3 in One", mrp: 1600, price: 320, category: "aerial", emoji: "🎇" },

  // ---- FANCY / KIDS ITEMS ----
  { id: 77, name: "Chotta Fancy", mrp: 395, price: 79, category: "fancy", emoji: "🎭" },
  { id: 78, name: "Photo Flash", mrp: 400, price: 80, category: "fancy", emoji: "📸" },
  { id: 79, name: "Colour Smoke", mrp: 1100, price: 220, category: "fancy", emoji: "🌈" },
  { id: 80, name: "Butterfly", mrp: 600, price: 120, category: "fancy", emoji: "🦋" },
  { id: 81, name: "Selfie Stick", mrp: 750, price: 150, category: "fancy", emoji: "🤳" },
  { id: 82, name: "Magic Show", mrp: 1600, price: 320, category: "fancy", emoji: "🎩" },
  { id: 83, name: "Cartoon Box", mrp: 400, price: 80, category: "fancy", emoji: "🎁" },
  { id: 84, name: "Kitkat", mrp: 850, price: 70, category: "fancy", emoji: "🍫" },
  { id: 85, name: "Pops", mrp: 70, price: 14, category: "fancy", emoji: "🎈" },
  { id: 86, name: "Pop Corn", mrp: 400, price: 80, category: "fancy", emoji: "🍿" },
  { id: 87, name: "Magic Feathers", mrp: 480, price: 96, category: "fancy", emoji: "🪶" },
  { id: 88, name: "Dancing Spinner", mrp: 600, price: 120, category: "fancy", emoji: "💃" },
  { id: 89, name: "Spl Bat Pencil Shower", mrp: 1200, price: 240, category: "fancy", emoji: "🏏" },
  { id: 90, name: "Special Shower", mrp: 800, price: 160, category: "fancy", emoji: "🚿" },
  { id: 91, name: "Water Falls", mrp: 1800, price: 220, category: "fancy", emoji: "💦" },
  { id: 92, name: "Drone", mrp: 1300, price: 260, category: "fancy", emoji: "🚁" },
  { id: 93, name: "Helicopter", mrp: 650, price: 130, category: "fancy", emoji: "🚁" },
  { id: 94, name: "Tri Colour", mrp: 1600, price: 320, category: "fancy", emoji: "🎨" },
  { id: 95, name: "Colour Pinjore", mrp: 1700, price: 214, category: "fancy", emoji: "🎨" },
  { id: 96, name: "Peacock Shower", mrp: 1200, price: 240, category: "fancy", emoji: "🦚" },
  { id: 97, name: "Bada Peacock", mrp: 2800, price: 560, category: "fancy", emoji: "🦚" },
  { id: 98, name: "Pentagon", mrp: 1300, price: 260, category: "fancy", emoji: "⭐" },
  { id: 99, name: "White House", mrp: 1300, price: 260, category: "fancy", emoji: "🏠" },
  { id: 100, name: "Holly Night", mrp: 1300, price: 260, category: "fancy", emoji: "🌙" },
  { id: 101, name: "Black and White", mrp: 1200, price: 240, category: "fancy", emoji: "🎭" },
  { id: 102, name: "Black Forest", mrp: 1200, price: 240, category: "fancy", emoji: "🌲" },
  { id: 103, name: "Lollipop", mrp: 1200, price: 240, category: "fancy", emoji: "🍭" },
  { id: 104, name: "Lollipop Stick", mrp: 1200, price: 240, category: "fancy", emoji: "🍭" },
  { id: 105, name: "Skoda / Swift", mrp: 1200, price: 240, category: "fancy", emoji: "🚗" },
  { id: 106, name: "Star Drum", mrp: 640, price: 128, category: "fancy", emoji: "⭐" },
  { id: 107, name: "7 Shot", mrp: 1300, price: 260, category: "aerial", emoji: "🎆" },
  { id: 108, name: "Animal Shower", mrp: 3495, price: 699, category: "fancy", emoji: "🐘" },
  { id: 109, name: "Temple Run Shower", mrp: 3995, price: 799, category: "fancy", emoji: "🏛️" },
  { id: 110, name: "Talking Tom", mrp: 3995, price: 799, category: "fancy", emoji: "😺" },
  { id: 111, name: "Nemo Candle", mrp: 6995, price: 1399, category: "fancy", emoji: "🐠" },
  { id: 112, name: "Tin Shower", mrp: 1240, price: 249, category: "fancy", emoji: "🎇" },
  { id: 113, name: "Avengers", mrp: 2945, price: 589, category: "fancy", emoji: "🦸" },
  { id: 114, name: "Angry Bird", mrp: 2095, price: 419, category: "fancy", emoji: "🐦" },
  { id: 115, name: "Forza", mrp: 4995, price: 999, category: "fancy", emoji: "🏎️" },
  { id: 116, name: "Kids 1000", mrp: 1250, price: 250, category: "fancy", emoji: "👶" },
  { id: 117, name: "Spl Gujarat Chatti Small", mrp: 1300, price: 260, category: "fancy", emoji: "🎀" },
  { id: 118, name: "Spl Gujarat Chatti Big", mrp: 1600, price: 320, category: "fancy", emoji: "🎀" },
  { id: 119, name: "Spl Gujarat Chatti Mega", mrp: 5200, price: 1040, category: "fancy", emoji: "🎀" },
  { id: 120, name: "Lava / Reno / Undo", mrp: 950, price: 192, category: "fancy", emoji: "🌋" },
  { id: 121, name: "Peacock Feathers", mrp: 480, price: 96, category: "fancy", emoji: "🦚" },
  { id: 122, name: "Tweet", mrp: 800, price: 160, category: "fancy", emoji: "🐦" },
  { id: 123, name: "Poppings", mrp: 800, price: 160, category: "fancy", emoji: "🎊" },
  { id: 124, name: "Golden Peacock", mrp: 800, price: 160, category: "fancy", emoji: "🦚" },
  { id: 125, name: "Jolly Ranger", mrp: 800, price: 160, category: "fancy", emoji: "🤠" },
  { id: 126, name: "7 Wonder", mrp: 800, price: 160, category: "fancy", emoji: "🗺️" },
  { id: 127, name: "Siren Big (3 pcs)", mrp: 1000, price: 200, category: "fancy", emoji: "🚨" },
  { id: 128, name: "Pappu Shower", mrp: 1250, price: 250, category: "fancy", emoji: "🚿" },
  { id: 129, name: "Special Fancy Gun", mrp: 1200, price: 240, category: "fancy", emoji: "🔫" },
  { id: 130, name: "SS Shower", mrp: 600, price: 120, category: "fancy", emoji: "🎇" },
  { id: 131, name: "Laptop", mrp: 1745, price: 349, category: "fancy", emoji: "💻" },
  { id: 132, name: "5 In One", mrp: 1300, price: 260, category: "fancy", emoji: "🎁" },
  { id: 133, name: "10 In One", mrp: 2600, price: 520, category: "fancy", emoji: "🎁" },
  { id: 134, name: "10 In One Multicolour", mrp: 1995, price: 399, category: "fancy", emoji: "🌈" },
  { id: 135, name: "5 In One Multicolour", mrp: 1995, price: 399, category: "fancy", emoji: "🌈" },

  // ---- SPARKLERS ----
  { id: 136, name: "7 Cm Electric Sparklers", mrp: 55, price: 11, category: "sparkler", emoji: "✨" },
  { id: 137, name: "7 Cm Colour Sparklers", mrp: 80, price: 16, category: "sparkler", emoji: "✨" },
  { id: 138, name: "10 Cm Electric Sparklers", mrp: 90, price: 18, category: "sparkler", emoji: "✨" },
  { id: 139, name: "10 Cm Colour Sparklers", mrp: 140, price: 28, category: "sparkler", emoji: "✨" },
  { id: 140, name: "12 Cm Electric Sparklers", mrp: 150, price: 30, category: "sparkler", emoji: "✨" },
  { id: 141, name: "12 Cm Colour Sparklers", mrp: 200, price: 40, category: "sparkler", emoji: "✨" },
  { id: 142, name: "15 Cm Electric Sparklers", mrp: 260, price: 52, category: "sparkler", emoji: "✨" },
  { id: 143, name: "15 Cm Colour Sparklers", mrp: 340, price: 68, category: "sparkler", emoji: "✨" },
  { id: 144, name: "30 Cm Electric Sparklers", mrp: 260, price: 52, category: "sparkler", emoji: "✨" },
  { id: 145, name: "30 Cm Colour Sparklers", mrp: 340, price: 68, category: "sparkler", emoji: "✨" },
  { id: 146, name: "15 Cm Green Sparklers", mrp: 260, price: 62, category: "sparkler", emoji: "💚" },
  { id: 147, name: "15 Cm Red Sparklers", mrp: 340, price: 78, category: "sparkler", emoji: "❤️" },
  { id: 148, name: "30 Cm Green Sparklers", mrp: 260, price: 62, category: "sparkler", emoji: "💚" },
  { id: 149, name: "30 Cm Red Sparklers", mrp: 340, price: 78, category: "sparkler", emoji: "❤️" },
  { id: 150, name: "50 Cm Electric Sparklers", mrp: 1130, price: 226, category: "sparkler", emoji: "✨" },
  { id: 151, name: "50 Cm Colour Sparklers", mrp: 1540, price: 308, category: "sparkler", emoji: "✨" },
];
